##########
#
# Auth0 Management API
#
# https://auth0.com/docs/api/management/v2
#
##########


# Get access token
# @name token
POST https://{{tenant}}/oauth/token
Content-Type: application/json

{
    "client_id": "{{admin_client_id}}",
    "client_secret": "{{admin_client_secret}}",
    "audience": "https://{{tenant}}/api/v2/",
    "grant_type": "client_credentials"
}

@access_token = {{token.response.body.$.access_token}}

###

# Create Ressource Owner Password App
# @name create
POST https://{{tenant}}/api/v2/clients
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "name": "Ressource Owner App",
    "token_endpoint_auth_method": "client_secret_post",
    "oidc_conformant": true,
    "token_endpoint_auth_method": "client_secret_post",
    "app_type": "regular_web",
    "grant_types": [
        "http://auth0.com/oauth/grant-type/password-realm",
        "password",
        "refresh_token"
    ],
    "is_first_party": true
}

@client_id = {{create.response.body.$.client_id}}

###

# Create client grant

POST https://{{tenant}}/api/v2/client-grants
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "client_id": "{{client_id}}",
  "audience": "calculator-api",
  "scope": [
    "calc:double",
    "calc:square"
  ]
}

###

PATCH https://{{tenant}}/api/v2/clients/{{client_id}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "grant_types": [
        "refresh_token",
        "password",
        "http://auth0.com/oauth/grant-type/password-realm"
    ]
}

###

GET https://{{tenant}}/api/v2/clients/{{client_id}}
Authorization: Bearer {{access_token}}
