##########
#
# Client Credentials Grant
#
# https://auth0.com/docs/api-auth/tutorials/client-credentials
#
##########


#####
# Configuration --> use Machine-to-Machine in Auth0

@client_id= WJZ8apZtVYl7Um5IhDiZyL4pf4Tvserf
@client_secret = KfHj6AETs1hN9vs6TagMT-20CQd1xbkr-Csgbdc4ke_16Q8Gcqc3Gnxy5ebqYnD9
@client_id2= wqB2hYtfm2BVQ7GP07XPjO664uEKEthr
@client_secret2 = Lpj5AsJChxquoVitWJJLL_rpawjIZpHbSn8K4zP-vHUmDPNHE6jhIFo4WrZk5UbG

#
#####


# Get Access Token for Client (double-only)
# @name token 
POST https://{{tenant}}/oauth/token
Content-Type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "{{client_id}}",
    "client_secret": "{{client_secret}}",
    "audience": "{{audience}}",
    "scope" : "calc:double"
}

###

@access_token = {{token.response.body.$.access_token}}

# Double Calucator API
GET http://localhost:5001/api/double/3
Authorization: Bearer {{access_token}}

###

# Square Calucator API
GET http://localhost:5001/api/square/3
Authorization: Bearer {{access_token}}

###

# Tokeninfo Calucator API
GET http://localhost:5001/api/tokeninfo
Authorization: Bearer {{access_token}}

###

# Get Access Token for Client (double and square)
# @name token2
POST https://{{tenant}}/oauth/token
Content-Type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "{{client_id2}}",
    "client_secret": "{{client_secret2}}",
    "audience": "calculator-api",
    "scope" : "calc:double calc:square"
}

###

@access_token2 = {{token2.response.body.$.access_token}}

# Double Calucator API
GET http://localhost:5001/api/double/3
Authorization: Bearer {{access_token2}}


###

# Square Calucator API
GET http://localhost:5001/api/square/3
Authorization: Bearer {{access_token2}}

###

# Tokeninfo Calucator API
GET http://localhost:5001/api/tokeninfo
Authorization: Bearer {{access_token2}}
