##########
#
# Auth0 Management API
#
# https://auth0.com/docs/api/management/v2
#
##########


#####
# Configuration --> use Admin Api Client
# see https://auth0.com/docs/api/management/v2/tokens 

@tenant = apisummit.eu.auth0.com
@admin_client_id= PkYF3L4dYwsL7v7KHSF0uO2tP1iZPw2t
@admin_client_secret = CLYYR-lm3_XyINAmtSyD_x-LSObnL6O08lTkVLgyxFdIbOJt_bFvvZ5Ofhlac0RJ

#
#####


# Get access token
# @name token
POST https://{{tenant}}/oauth/token
Content-Type: application/json

{
    "client_id": "{{admin_client_id}}",
    "client_secret": "{{admin_client_secret}}",
    "audience": "https://apisummit.eu.auth0.com/api/v2/",
    "grant_type": "client_credentials"
}

@access_token = {{token.response.body.$.access_token}}

###

# Get all clients
GET https://{{tenant}}/api/v2/clients
Authorization: Bearer {{access_token}}

###

# Create resource server

POST https://{{tenant}}/api/v2/resource-servers
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "name": "Calculator API",
    "identifier": "calculator-api",
    "allow_offline_access": true,
    "skip_consent_for_verifiable_first_party_clients": true,
    "scopes": [{
            "value": "calc:square",
            "description": "Calculate square"
        },
        {
            "value": "calc:double",
            "description": "Calculate double"
        }
    ]
}


###

# Create machine-to-machine client (simple)
# @name create_m2m_simple
POST https://{{tenant}}/api/v2/clients
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "Client simple",
  "token_endpoint_auth_method": "client_secret_post",
  "app_type": "non_interactive",
  "grant_types": [
    "authorization_code",
    "implicit",
    "refresh_token",
    "client_credentials"
  ],
  "is_first_party": true
}

@m2m_simple_client_id = {{create_m2m_simple.response.body.$.client_id}}

###

# Create client grant

POST https://{{tenant}}/api/v2/client-grants
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "client_id": "{{m2m_simple_client_id}}",
  "audience": "calculator-api",
  "scope": [
    "calc:double"
  ]
}

###

# Create machine-to-machine client (advanced)
# @name create_m2m_advanced
POST https://{{tenant}}/api/v2/clients
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "Client advanced",
  "token_endpoint_auth_method": "client_secret_post",
  "app_type": "non_interactive",
  "grant_types": [
    "authorization_code",
    "implicit",
    "refresh_token",
    "client_credentials"
  ],
  "is_first_party": true
}

@m2m_advanced_client_id = {{create_m2m_advanced.response.body.$.client_id}}

###

# Create client grant

POST https://{{tenant}}/api/v2/client-grants
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "client_id": "{{m2m_advanced_client_id}}",
  "audience": "calculator-api",
  "scope": [
    "calc:double",
    "calc:square"
  ]
}

###

# Create Ressource Owner Password App
# @name create_ropc
POST https://{{tenant}}/api/v2/clients
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "name": "Ressource Owner App",
    "token_endpoint_auth_method": "client_secret_post",
    "oidc_conformant": true,
    "token_endpoint_auth_method": "client_secret_post",
    "app_type": "regular_web",
    "grant_types": [
        "authorization_code",
        "client_credentials",
        "http://auth0.com/oauth/grant-type/password-realm",
        "implicit",
        "password",
        "refresh_token"
    ],
    "is_first_party": true
}

@ropc_client_id = {{create_ropc.response.body.$.client_id}}

###

# Create client grant

POST https://{{tenant}}/api/v2/client-grants
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "client_id": "{{ropc_client_id}}",
  "audience": "calculator-api",
  "scope": [
    "calc:double",
    "calc:square"
  ]
}

###

PATCH https://{{tenant}}/api/v2/clients/{{client_id}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "grant_types": [
        "authorization_code",
        "implicit",
        "refresh_token",
        "password",
        "http://auth0.com/oauth/grant-type/password-realm"
    ]
}


###

# Create  Web App
# @name create_webapp
POST https://{{tenant}}/api/v2/clients
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "is_token_endpoint_ip_header_trusted": false,
    "name": "xxxWeb Application",
    "is_first_party": true,
    "oidc_conformant": true,
    "callbacks": [
        "http://localhost:3000/signin-auth0"
    ],
    "allowed_logout_urls": [
        "http://localhost:3000/"
    ],
    "token_endpoint_auth_method": "client_secret_post",
    "app_type": "regular_web",
    "grant_types": [
        "authorization_code",
        "refresh_token"
    ],
    "custom_login_page_on": true
}

@webapp_client_id = {{create_webapp.response.body.$.client_id}}

###

GET https://{{tenant}}/api/v2/clients/{{client_id}}
Authorization: Bearer {{access_token}}
