##########
#
# Auth0 Management API
#
# https://auth0.com/docs/api/management/v2
#
##########


#####
# Configuration --> use Admin Api Client

@tenant = apisummit.eu.auth0.com
@admin_client_id= rOolHLh9eJ7s60DQzK7bpdRPx0wiJCON
@admin_client_secret = YOUR_CLIENT_SECRET

@client_id = U2avzP9EfL2ZjmpbhZlz7Md74CCpHSfJ

#
#####


# Get access token
# @name token
POST https://{{tenant}}/oauth/token
Content-Type: application/json

{
    "client_id": "{{admin_client_id}}",
    "client_secret": "{{admin_client_secret}}",
    "audience": "https://apisummit.eu.auth0.com/api/v2/",
    "grant_type": "client_credentials"
}

@access_token = {{token.response.body.$.access_token}}

###

# Get all clients
GET https://{{tenant}}/api/v2/clients
Authorization: Bearer {{access_token}}

###

# Get a client
GET https://{{tenant}}/api/v2/clients/{{client_id}}
Authorization: Bearer {{access_token}}

###

PATCH https://{{tenant}}/api/v2/clients/{{client_id}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "grant_types": [
        "authorization_code",
        "implicit",
        "refresh_token",
        "password",
        "http://auth0.com/oauth/grant-type/password-realm"
    ]
}

###

GET https://{{tenant}}/api/v2/clients/{{client_id}}
Authorization: Bearer {{access_token}}
