#
# Client Credentials Grant
#
# https://auth0.com/docs/api-auth/tutorials/client-credentials
#

# Get Access Token for Client (double-only)
POST https://apisummit.eu.auth0.com/oauth/token
Content-Type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "WJZ8apZtVYl7Um5IhDiZyL4pf4Tvserf",
    "client_secret": "KfHj6AETs1hN9vs6TagMT-20CQd1xbkr-Csgbdc4ke_16Q8Gcqc3Gnxy5ebqYnD9",
    "audience": "calculator-api",
    "scope" : "calc:double"
}

###

# Double Calucator API
GET http://localhost:5001/api/double/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1FRkdRamN4UkVKRk9FRXdRMFUwTmpjME56bENNa016UmpFMFFUVTNNME16UlVSQk9ERXhNZyJ9.eyJpc3MiOiJodHRwczovL2FwaXN1bW1pdC5ldS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWJmMTMwZGM1YTAwYWYyMjE5ZGM5ZTUzIiwiYXVkIjpbImNhbGN1bGF0b3ItYXBpIiwiaHR0cHM6Ly9hcGlzdW1taXQuZXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTU0MjgzODYyNSwiZXhwIjoxNTQyODQ1ODI1LCJhenAiOiJldmh5OEJzZHZGbjNZeE83MTM4eTRHMFFMMkZPdzJoVCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgY2FsYzpzcXVhcmUifQ.cRPJ1g_dSoujeSoSEqh5iqxrVhKgnK9JbbljS8R6IMU6oWLw742YlivdtuvC3KJlIF9Ave-NRLZz9v2MAhaXzisY7ezCzzgmL8gckc4P1IaodoPEBexgSEpCP4GrlzU8yZHj8EYW-ktvv5GPjB67JqgflJverKCGxZMzwDi7IXFuukWxlhAmlmkX7GO7esUeqZg0ZdNX_GU9bjy-jwa0Cyrn8RhOQPrGKXmSlZ_bi5q6P6Mm4npWnLqw1hth8Cggg6LiYVCFWoZBJ5rW9_QuoQtspzQom45b4CkWuGAEwe4Pxba1DB5Vhr_-jGkjMCwFmrcR75k_9cwAOro6tYXWWg

###

# Square Calucator API
GET http://localhost:5001/api/square/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1FRkdRamN4UkVKRk9FRXdRMFUwTmpjME56bENNa016UmpFMFFUVTNNME16UlVSQk9ERXhNZyJ9.eyJpc3MiOiJodHRwczovL2FwaXN1bW1pdC5ldS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWJmMTMwZGM1YTAwYWYyMjE5ZGM5ZTUzIiwiYXVkIjpbImNhbGN1bGF0b3ItYXBpIiwiaHR0cHM6Ly9hcGlzdW1taXQuZXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTU0MjgzODYyNSwiZXhwIjoxNTQyODQ1ODI1LCJhenAiOiJldmh5OEJzZHZGbjNZeE83MTM4eTRHMFFMMkZPdzJoVCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgY2FsYzpzcXVhcmUifQ.cRPJ1g_dSoujeSoSEqh5iqxrVhKgnK9JbbljS8R6IMU6oWLw742YlivdtuvC3KJlIF9Ave-NRLZz9v2MAhaXzisY7ezCzzgmL8gckc4P1IaodoPEBexgSEpCP4GrlzU8yZHj8EYW-ktvv5GPjB67JqgflJverKCGxZMzwDi7IXFuukWxlhAmlmkX7GO7esUeqZg0ZdNX_GU9bjy-jwa0Cyrn8RhOQPrGKXmSlZ_bi5q6P6Mm4npWnLqw1hth8Cggg6LiYVCFWoZBJ5rW9_QuoQtspzQom45b4CkWuGAEwe4Pxba1DB5Vhr_-jGkjMCwFmrcR75k_9cwAOro6tYXWWg

###

# Tokeninfo Calucator API
GET http://localhost:5001/api/tokeninfo
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1FRkdRamN4UkVKRk9FRXdRMFUwTmpjME56bENNa016UmpFMFFUVTNNME16UlVSQk9ERXhNZyJ9.eyJpc3MiOiJodHRwczovL2FwaXN1bW1pdC5ldS5hdXRoMC5jb20vIiwic3ViIjoiV0paOGFwWnRWWWw3VW01SWhEaVp5TDRwZjRUdnNlcmZAY2xpZW50cyIsImF1ZCI6ImNhbGN1bGF0b3ItYXBpIiwiaWF0IjoxNTQyNDg3MTQ0LCJleHAiOjE1NDI1NzM1NDQsImF6cCI6IldKWjhhcFp0VllsN1VtNUloRGlaeUw0cGY0VHZzZXJmIiwic2NvcGUiOiJjYWxjOmRvdWJsZSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.FGczkA_mDmpqDuaqGYtXSBypGpCI9p9MDtQCmrdDHXMgXKVaaRP0LxOut0SgKgdIw-D9E9dcVXQGJ4BGB9NaxOvCsQalP4efp37XrT4tpyN78v93IX1fYltrqYTDDCWrNkw31NXk6RmqsBNmUp8YPSwvbTHSSKdusE_bceGvry44NIQqs1bs4Lgp1UYjSc2Bbh39mQhJ3R8zIvrS2H9xbVHgi1CsKwjSaghZzI4Cq0Tda3Ik9VR1YSmjkYhbfnVMfF-emcJHP6KmDXFTJ5_rfAWj8t6uHp_AvZ84wl8LmtX-Gqzd1LEOcLwgFP87DTkQCFAGFcI-5tVmqI6cddY1UA

###

# Get Access Token for Client (double and square)
POST https://apisummit.eu.auth0.com/oauth/token
Content-Type: application/json

{
    "grant_type": "client_credentials",
    "client_id": "wqB2hYtfm2BVQ7GP07XPjO664uEKEthr",
    "client_secret": "Lpj5AsJChxquoVitWJJLL_rpawjIZpHbSn8K4zP-vHUmDPNHE6jhIFo4WrZk5UbG",
    "audience": "calculator-api",
    "scope" : "calc:double calc:square"
}

###

# Double Calucator API
GET http://localhost:5001/api/double/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1FRkdRamN4UkVKRk9FRXdRMFUwTmpjME56bENNa016UmpFMFFUVTNNME16UlVSQk9ERXhNZyJ9.eyJpc3MiOiJodHRwczovL2FwaXN1bW1pdC5ldS5hdXRoMC5jb20vIiwic3ViIjoid3FCMmhZdGZtMkJWUTdHUDA3WFBqTzY2NHVFS0V0aHJAY2xpZW50cyIsImF1ZCI6ImNhbGN1bGF0b3ItYXBpIiwiaWF0IjoxNTQyNDg2NDM4LCJleHAiOjE1NDI1NzI4MzgsImF6cCI6IndxQjJoWXRmbTJCVlE3R1AwN1hQak82NjR1RUtFdGhyIiwic2NvcGUiOiJjYWxjOnNxdWFyZSBjYWxjOmRvdWJsZSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.JAcEaAX2WlbwACzhP87B7hOdt60naMyPjlYo5kZPubOaIdM6ffkSf-cSvrqqd4ZrTkpcvDgn_YyhFqnjt3pxBUdBdSFaWSayNy3byWlJz3YQK1GCBKwBU3lUfksncBc9XhWT0d8_WD33GnhY_kTSR3SrBDsu7ulCnyN9T8nQE5b29oX7d0tCnXKWGwWxgida9DW2qZaHva-6Lw1Fg9bZzDNADmjUgFCK4nSCYpKa5HDKdEry5Iw29JXtciZHiy9OhtZnNa7SCdgyBQuNwT3lF-LIttDHE83YpR8cE4-WVM0m4kQqw-Uss8T-ePhC3cnlZvnIP84FNBSFu8eE_ISbng

###

# Square Calucator API
GET http://localhost:5001/api/square/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1FRkdRamN4UkVKRk9FRXdRMFUwTmpjME56bENNa016UmpFMFFUVTNNME16UlVSQk9ERXhNZyJ9.eyJpc3MiOiJodHRwczovL2FwaXN1bW1pdC5ldS5hdXRoMC5jb20vIiwic3ViIjoid3FCMmhZdGZtMkJWUTdHUDA3WFBqTzY2NHVFS0V0aHJAY2xpZW50cyIsImF1ZCI6ImNhbGN1bGF0b3ItYXBpIiwiaWF0IjoxNTQyNDg2NDM4LCJleHAiOjE1NDI1NzI4MzgsImF6cCI6IndxQjJoWXRmbTJCVlE3R1AwN1hQak82NjR1RUtFdGhyIiwic2NvcGUiOiJjYWxjOnNxdWFyZSBjYWxjOmRvdWJsZSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.JAcEaAX2WlbwACzhP87B7hOdt60naMyPjlYo5kZPubOaIdM6ffkSf-cSvrqqd4ZrTkpcvDgn_YyhFqnjt3pxBUdBdSFaWSayNy3byWlJz3YQK1GCBKwBU3lUfksncBc9XhWT0d8_WD33GnhY_kTSR3SrBDsu7ulCnyN9T8nQE5b29oX7d0tCnXKWGwWxgida9DW2qZaHva-6Lw1Fg9bZzDNADmjUgFCK4nSCYpKa5HDKdEry5Iw29JXtciZHiy9OhtZnNa7SCdgyBQuNwT3lF-LIttDHE83YpR8cE4-WVM0m4kQqw-Uss8T-ePhC3cnlZvnIP84FNBSFu8eE_ISbng

###

# Tokeninfo Calucator API
GET http://localhost:5001/api/tokeninfo
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1FRkdRamN4UkVKRk9FRXdRMFUwTmpjME56bENNa016UmpFMFFUVTNNME16UlVSQk9ERXhNZyJ9.eyJpc3MiOiJodHRwczovL2FwaXN1bW1pdC5ldS5hdXRoMC5jb20vIiwic3ViIjoid3FCMmhZdGZtMkJWUTdHUDA3WFBqTzY2NHVFS0V0aHJAY2xpZW50cyIsImF1ZCI6ImNhbGN1bGF0b3ItYXBpIiwiaWF0IjoxNTQyNDg2NDM4LCJleHAiOjE1NDI1NzI4MzgsImF6cCI6IndxQjJoWXRmbTJCVlE3R1AwN1hQak82NjR1RUtFdGhyIiwic2NvcGUiOiJjYWxjOnNxdWFyZSBjYWxjOmRvdWJsZSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.JAcEaAX2WlbwACzhP87B7hOdt60naMyPjlYo5kZPubOaIdM6ffkSf-cSvrqqd4ZrTkpcvDgn_YyhFqnjt3pxBUdBdSFaWSayNy3byWlJz3YQK1GCBKwBU3lUfksncBc9XhWT0d8_WD33GnhY_kTSR3SrBDsu7ulCnyN9T8nQE5b29oX7d0tCnXKWGwWxgida9DW2qZaHva-6Lw1Fg9bZzDNADmjUgFCK4nSCYpKa5HDKdEry5Iw29JXtciZHiy9OhtZnNa7SCdgyBQuNwT3lF-LIttDHE83YpR8cE4-WVM0m4kQqw-Uss8T-ePhC3cnlZvnIP84FNBSFu8eE_ISbng
