##########
#
# Implict Grant
#
# https://auth0.com/docs/api-auth/tutorials/implicit-grant
#
##########


#####
# Configuration --> use Single Page App in Auth0

@client_id= OvyhJsTW2V7m7nN1Y2rBWtwPhSrcgWlZ
@redirect_uri = http://localhost:3000/signin-auth0

#
#####


# Get identity and access token
GET https://{{tenant}}/authorize?scope=openid%20email%20profile%20calc%3Asquare&audience={{audience}}&response_type=id_token%20token&client_id={{client_id}}&redirect_uri={{redirect_uri}}&nonce=12345789&prompt=consent

@access_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1FRkdRamN4UkVKRk9FRXdRMFUwTmpjME56bENNa016UmpFMFFUVTNNME16UlVSQk9ERXhNZyJ9.eyJpc3MiOiJodHRwczovL2FwaXN1bW1pdC5ldS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWJmMTMwZGM1YTAwYWYyMjE5ZGM5ZTUzIiwiYXVkIjpbImNhbGN1bGF0b3ItYXBpIiwiaHR0cHM6Ly9hcGlzdW1taXQuZXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTU3NTIzMzkxMiwiZXhwIjoxNTc1MjQxMTEyLCJhenAiOiJPdnloSnNUVzJWN203bk4xWTJyQld0d1BoU3JjZ1dsWiIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgY2FsYzpzcXVhcmUifQ.iRYo0j_g7aLZRz05S7huwmvGUPN9hrRJWyzDeXyRwMmf-iVhbJo4dqjF1J0nE5ilPl-vyPpZUSqUQ1dQBubwpTlLfqvKykokAhP1ybhfPpXl6eM1TtKIulcxmC9MwKbVuY4X7SqYiw9rGqsrI42SBvzmaf9DuezBIQYHaLg4jQ0mPPb1xjCXSEDMVgRG1JhqX5OA9rz6x_rvV7D4ieP0BpheQBMjq94AOqu5NBRtTmM8WhO6Kbm8C5-_-dN3uKCf-__hLXUTuTwqXRgXB9jvkRAVI9Ki6qoTsESUjO8BLeTI6AyNlyPfS1h8LghNnVW814Gyrls9rpc_ZV3GIFQMyg

###

# Get Userinfo with identity token
GET https://{{tenant}}/userinfo
Authorization: Bearer {{access_token}}

###

# Double Calucator API
GET http://localhost:5001/api/double/3
Authorization: Bearer {{access_token}}

###

# Square Calucator API
GET http://localhost:5001/api/square/3
Authorization: Bearer {{access_token}}

###

# Tokeninfo Calucator API
GET http://localhost:5001/api/tokeninfo
Authorization: Bearer {{access_token}}
