#
# Implict Grant
#
# https://auth0.com/docs/api-auth/tutorials/implicit-grant
#


# Get identity and access token
GET https://apisummit.eu.auth0.com/authorize?scope=openid%20email%20profile%20calc%3Asquare&audience=calculator-api&response_type=id_token%20token&client_id=evhy8BsdvFn3YxO7138y4G0QL2FOw2hT&redirect_uri=https://localhost:5002/signincallback&nonce=12345789&prompt=consent

# Get Userinfo with identity token
GET https://apisummit.eu.auth0.com/userinfo
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1FRkdRamN4UkVKRk9FRXdRMFUwTmpjME56bENNa016UmpFMFFUVTNNME16UlVSQk9ERXhNZyJ9.eyJpc3MiOiJodHRwczovL2FwaXN1bW1pdC5ldS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWJmMTMwZGM1YTAwYWYyMjE5ZGM5ZTUzIiwiYXVkIjpbImNhbGN1bGF0b3ItYXBpIiwiaHR0cHM6Ly9hcGlzdW1taXQuZXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTU0MjgzOTIyMiwiZXhwIjoxNTQyODQ2NDIyLCJhenAiOiJldmh5OEJzZHZGbjNZeE83MTM4eTRHMFFMMkZPdzJoVCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgY2FsYzpzcXVhcmUifQ.eFIDvA7rVuwlBYRsI-UfdGfGZSWrVH0__DoRefRDgbCndvoy6cXU0bSBu8dfeBfQHQ8UWMbEm6ixTZho7CYPL0QaFOadupQ5a7IYs2p14jzrsoF_59qRN4Yd8M5Dw4MCDYEnxKgjPBkScAqUgO97BlzKD8c7u96iWYxO9lx4iyjJp2361-heoewgn0di-YKoeQ_Y7vZPwh7-jBH-OQEMKIth6sUoFuU-9hP_h40xIr0Hou3Eqqo2Fz1R3kV7-KzHDGc1it8kR-kTrTuRyrCFXj9nvNHWkoJ6tC2JVS7c-rfYkehfEQjHUvExrU1Wb4-lVhTFrsAPPfrVUQvlobKaqg

# Double Calucator API
GET http://localhost:5001/api/double/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1FRkdRamN4UkVKRk9FRXdRMFUwTmpjME56bENNa016UmpFMFFUVTNNME16UlVSQk9ERXhNZyJ9.eyJpc3MiOiJodHRwczovL2FwaXN1bW1pdC5ldS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWJmMTMwZGM1YTAwYWYyMjE5ZGM5ZTUzIiwiYXVkIjpbImNhbGN1bGF0b3ItYXBpIiwiaHR0cHM6Ly9hcGlzdW1taXQuZXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTU0MjgzOTIyMiwiZXhwIjoxNTQyODQ2NDIyLCJhenAiOiJldmh5OEJzZHZGbjNZeE83MTM4eTRHMFFMMkZPdzJoVCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgY2FsYzpzcXVhcmUifQ.eFIDvA7rVuwlBYRsI-UfdGfGZSWrVH0__DoRefRDgbCndvoy6cXU0bSBu8dfeBfQHQ8UWMbEm6ixTZho7CYPL0QaFOadupQ5a7IYs2p14jzrsoF_59qRN4Yd8M5Dw4MCDYEnxKgjPBkScAqUgO97BlzKD8c7u96iWYxO9lx4iyjJp2361-heoewgn0di-YKoeQ_Y7vZPwh7-jBH-OQEMKIth6sUoFuU-9hP_h40xIr0Hou3Eqqo2Fz1R3kV7-KzHDGc1it8kR-kTrTuRyrCFXj9nvNHWkoJ6tC2JVS7c-rfYkehfEQjHUvExrU1Wb4-lVhTFrsAPPfrVUQvlobKaqg

# Square Calucator API
GET http://localhost:5001/api/square/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1FRkdRamN4UkVKRk9FRXdRMFUwTmpjME56bENNa016UmpFMFFUVTNNME16UlVSQk9ERXhNZyJ9.eyJpc3MiOiJodHRwczovL2FwaXN1bW1pdC5ldS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWJmMTMwZGM1YTAwYWYyMjE5ZGM5ZTUzIiwiYXVkIjpbImNhbGN1bGF0b3ItYXBpIiwiaHR0cHM6Ly9hcGlzdW1taXQuZXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTU0MjgzOTIyMiwiZXhwIjoxNTQyODQ2NDIyLCJhenAiOiJldmh5OEJzZHZGbjNZeE83MTM4eTRHMFFMMkZPdzJoVCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgY2FsYzpzcXVhcmUifQ.eFIDvA7rVuwlBYRsI-UfdGfGZSWrVH0__DoRefRDgbCndvoy6cXU0bSBu8dfeBfQHQ8UWMbEm6ixTZho7CYPL0QaFOadupQ5a7IYs2p14jzrsoF_59qRN4Yd8M5Dw4MCDYEnxKgjPBkScAqUgO97BlzKD8c7u96iWYxO9lx4iyjJp2361-heoewgn0di-YKoeQ_Y7vZPwh7-jBH-OQEMKIth6sUoFuU-9hP_h40xIr0Hou3Eqqo2Fz1R3kV7-KzHDGc1it8kR-kTrTuRyrCFXj9nvNHWkoJ6tC2JVS7c-rfYkehfEQjHUvExrU1Wb4-lVhTFrsAPPfrVUQvlobKaqg

# Tokeninfo Calucator API
GET http://localhost:5001/api/tokeninfo
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1FRkdRamN4UkVKRk9FRXdRMFUwTmpjME56bENNa016UmpFMFFUVTNNME16UlVSQk9ERXhNZyJ9.eyJpc3MiOiJodHRwczovL2FwaXN1bW1pdC5ldS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWJmMTMwZGM1YTAwYWYyMjE5ZGM5ZTUzIiwiYXVkIjpbImNhbGN1bGF0b3ItYXBpIiwiaHR0cHM6Ly9hcGlzdW1taXQuZXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTU0MjgzOTIyMiwiZXhwIjoxNTQyODQ2NDIyLCJhenAiOiJldmh5OEJzZHZGbjNZeE83MTM4eTRHMFFMMkZPdzJoVCIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwgY2FsYzpzcXVhcmUifQ.eFIDvA7rVuwlBYRsI-UfdGfGZSWrVH0__DoRefRDgbCndvoy6cXU0bSBu8dfeBfQHQ8UWMbEm6ixTZho7CYPL0QaFOadupQ5a7IYs2p14jzrsoF_59qRN4Yd8M5Dw4MCDYEnxKgjPBkScAqUgO97BlzKD8c7u96iWYxO9lx4iyjJp2361-heoewgn0di-YKoeQ_Y7vZPwh7-jBH-OQEMKIth6sUoFuU-9hP_h40xIr0Hou3Eqqo2Fz1R3kV7-KzHDGc1it8kR-kTrTuRyrCFXj9nvNHWkoJ6tC2JVS7c-rfYkehfEQjHUvExrU1Wb4-lVhTFrsAPPfrVUQvlobKaqg
