#
# Ressource Owner Password Grant
#
# https://auth0.com/docs/api-auth/tutorials/password-grant
#

# Get Access Token for Ressource Owner App
POST https://apisummit.eu.auth0.com/oauth/token
Content-Type: application/json

{
    "grant_type": "password",
    "client_id": "U2avzP9EfL2ZjmpbhZlz7Md74CCpHSfJ",
    "client_secret": "HYEU0gHuDzkk-mU25e4yGlJlrlUney-sVx-zayeaO06SD9RP4uFmaF1S5IG0__By",
    "username": "johndoe@acme.inc",
    "password": "super!s3cr3t",
    "scope": "openid email profile",
    "audience": "calculator-api"
}

###

# Get Access Token for Ressource Owner App
POST https://apisummit.eu.auth0.com/oauth/token
Content-Type: application/json

{
    "grant_type": "password",
    "client_id": "U2avzP9EfL2ZjmpbhZlz7Md74CCpHSfJ",
    "client_secret": "HYEU0gHuDzkk-mU25e4yGlJlrlUney-sVx-zayeaO06SD9RP4uFmaF1S5IG0__By",
    "username": "johndoe@acme.inc",
    "password": "super!s3cr3t",
    "scope": "openid email profile offline_access",
    "audience": "calculator-api"
}


###

# Double Calucator API
GET http://localhost:5001/api/double/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1FRkdRamN4UkVKRk9FRXdRMFUwTmpjME56bENNa016UmpFMFFUVTNNME16UlVSQk9ERXhNZyJ9.eyJpc3MiOiJodHRwczovL2FwaXN1bW1pdC5ldS5hdXRoMC5jb20vIiwic3ViIjoid3FCMmhZdGZtMkJWUTdHUDA3WFBqTzY2NHVFS0V0aHJAY2xpZW50cyIsImF1ZCI6ImNhbGN1bGF0b3ItYXBpIiwiaWF0IjoxNTQyNDg2NDM4LCJleHAiOjE1NDI1NzI4MzgsImF6cCI6IndxQjJoWXRmbTJCVlE3R1AwN1hQak82NjR1RUtFdGhyIiwic2NvcGUiOiJjYWxjOnNxdWFyZSBjYWxjOmRvdWJsZSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.JAcEaAX2WlbwACzhP87B7hOdt60naMyPjlYo5kZPubOaIdM6ffkSf-cSvrqqd4ZrTkpcvDgn_YyhFqnjt3pxBUdBdSFaWSayNy3byWlJz3YQK1GCBKwBU3lUfksncBc9XhWT0d8_WD33GnhY_kTSR3SrBDsu7ulCnyN9T8nQE5b29oX7d0tCnXKWGwWxgida9DW2qZaHva-6Lw1Fg9bZzDNADmjUgFCK4nSCYpKa5HDKdEry5Iw29JXtciZHiy9OhtZnNa7SCdgyBQuNwT3lF-LIttDHE83YpR8cE4-WVM0m4kQqw-Uss8T-ePhC3cnlZvnIP84FNBSFu8eE_ISbng

###

# Square Calucator API
GET http://localhost:5001/api/square/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1FRkdRamN4UkVKRk9FRXdRMFUwTmpjME56bENNa016UmpFMFFUVTNNME16UlVSQk9ERXhNZyJ9.eyJpc3MiOiJodHRwczovL2FwaXN1bW1pdC5ldS5hdXRoMC5jb20vIiwic3ViIjoid3FCMmhZdGZtMkJWUTdHUDA3WFBqTzY2NHVFS0V0aHJAY2xpZW50cyIsImF1ZCI6ImNhbGN1bGF0b3ItYXBpIiwiaWF0IjoxNTQyNDg2NDM4LCJleHAiOjE1NDI1NzI4MzgsImF6cCI6IndxQjJoWXRmbTJCVlE3R1AwN1hQak82NjR1RUtFdGhyIiwic2NvcGUiOiJjYWxjOnNxdWFyZSBjYWxjOmRvdWJsZSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.JAcEaAX2WlbwACzhP87B7hOdt60naMyPjlYo5kZPubOaIdM6ffkSf-cSvrqqd4ZrTkpcvDgn_YyhFqnjt3pxBUdBdSFaWSayNy3byWlJz3YQK1GCBKwBU3lUfksncBc9XhWT0d8_WD33GnhY_kTSR3SrBDsu7ulCnyN9T8nQE5b29oX7d0tCnXKWGwWxgida9DW2qZaHva-6Lw1Fg9bZzDNADmjUgFCK4nSCYpKa5HDKdEry5Iw29JXtciZHiy9OhtZnNa7SCdgyBQuNwT3lF-LIttDHE83YpR8cE4-WVM0m4kQqw-Uss8T-ePhC3cnlZvnIP84FNBSFu8eE_ISbng

###

# Tokeninfo Calucator API
GET http://localhost:5001/api/tokeninfo
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1FRkdRamN4UkVKRk9FRXdRMFUwTmpjME56bENNa016UmpFMFFUVTNNME16UlVSQk9ERXhNZyJ9.eyJpc3MiOiJodHRwczovL2FwaXN1bW1pdC5ldS5hdXRoMC5jb20vIiwic3ViIjoid3FCMmhZdGZtMkJWUTdHUDA3WFBqTzY2NHVFS0V0aHJAY2xpZW50cyIsImF1ZCI6ImNhbGN1bGF0b3ItYXBpIiwiaWF0IjoxNTQyNDg2NDM4LCJleHAiOjE1NDI1NzI4MzgsImF6cCI6IndxQjJoWXRmbTJCVlE3R1AwN1hQak82NjR1RUtFdGhyIiwic2NvcGUiOiJjYWxjOnNxdWFyZSBjYWxjOmRvdWJsZSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.JAcEaAX2WlbwACzhP87B7hOdt60naMyPjlYo5kZPubOaIdM6ffkSf-cSvrqqd4ZrTkpcvDgn_YyhFqnjt3pxBUdBdSFaWSayNy3byWlJz3YQK1GCBKwBU3lUfksncBc9XhWT0d8_WD33GnhY_kTSR3SrBDsu7ulCnyN9T8nQE5b29oX7d0tCnXKWGwWxgida9DW2qZaHva-6Lw1Fg9bZzDNADmjUgFCK4nSCYpKa5HDKdEry5Iw29JXtciZHiy9OhtZnNa7SCdgyBQuNwT3lF-LIttDHE83YpR8cE4-WVM0m4kQqw-Uss8T-ePhC3cnlZvnIP84FNBSFu8eE_ISbng

###

# Refresh Token for Ressource Owner App
POST https://apisummit.eu.auth0.com/oauth/token
Content-Type: application/json

{
    "grant_type": "refresh_token",
    "client_id": "U2avzP9EfL2ZjmpbhZlz7Md74CCpHSfJ",
    "client_secret": "HYEU0gHuDzkk-mU25e4yGlJlrlUney-sVx-zayeaO06SD9RP4uFmaF1S5IG0__By",
    "refresh_token": "c4JHUtBNpK-mv6ETnbmGkXlO9zZeDbxvSmJclgEXBxRtu"
}


###

# Get Userinfo with access token
GET https://apisummit.eu.auth0.com/userinfo
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1FRkdRamN4UkVKRk9FRXdRMFUwTmpjME56bENNa016UmpFMFFUVTNNME16UlVSQk9ERXhNZyJ9.eyJpc3MiOiJodHRwczovL2FwaXN1bW1pdC5ldS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWJmMTMwZGM1YTAwYWYyMjE5ZGM5ZTUzIiwiYXVkIjpbImNhbGN1bGF0b3ItYXBpIiwiaHR0cHM6Ly9hcGlzdW1taXQuZXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTU0MjgzMjcyNSwiZXhwIjoxNTQyOTE5MTI1LCJhenAiOiJVMmF2elA5RWZMMlpqbXBiaFpsejdNZDc0Q0NwSFNmSiIsInNjb3BlIjoib3BlbmlkIGVtYWlsIGNhbGM6c3F1YXJlIGNhbGM6ZG91YmxlIiwiZ3R5IjoicGFzc3dvcmQifQ.P7aHOkYEfDHGmQN72nvRU6no0zO-FB0JDjOpAFBG_8qIHtKjtb2MBkGAIAX1DMlYx5U2e9dmdlxnRhulLV7LTcYHHxvtubuRVNLRriwsf91NDFzipDQ85IhKeckLrGl6PIGeM21o0Kxcxv4kefmDyUGKbqFm69SjstqysozUYDTY-G0Vf9kD_LKqXg7kJPwzuhpOvCGpmt5pLTao8-GB8vOahChhDPuS_FbhHaUgNnkKTkR3WuiXGIa_4O80HzY9nXowqSGaSclVnhy_bQpbvvZ6X95mh9Y-erDab8FDwNDwrI0vV5Bb9-XCUWb_eChmH2GAAfoUaXVc5cDsSj8BoA
