##########
#
# Ressource Owner Password Grant
#
# https://auth0.com/docs/api-auth/tutorials/password-grant
#
##########


#####
# Configuration --> use Regular Web App in Auth0
# requires manual configuration of password flow, see auth0-management-api.http

@tenant = apisummit.eu.auth0.com
@client_id= U2avzP9EfL2ZjmpbhZlz7Md74CCpHSfJ
@client_secret = HYEU0gHuDzkk-mU25e4yGlJlrlUney-sVx-zayeaO06SD9RP4uFmaF1S5IG0__By
@username = johndoe@acme.inc
@password = super!s3cr3t


#
#####


# Get Access Token for Ressource Owner App
# @name token
POST https://apisummit.eu.auth0.com/oauth/token
Content-Type: application/json

{
    "grant_type": "password",
    "client_id": "{{client_id}}",
    "client_secret": "{{client_secret}}",
    "username": "{{username}}",
    "password": "{{password}}",
    "scope": "openid email profile",
    "audience": "calculator-api"
}

@access_token = {{token.response.body.$.access_token}}
@id_token = {{token.response.body.$.id_token}}

###

# Get Userinfo with access token
GET https://apisummit.eu.auth0.com/userinfo
Authorization: Bearer {{access_token}}

###

# Get Access Token for Ressource Owner App
# @name token2
POST https://apisummit.eu.auth0.com/oauth/token
Content-Type: application/json

{
    "grant_type": "password",
    "client_id": "{{client_id}}",
    "client_secret": "{{client_secret}}",
    "username": "{{username}}",
    "password": "{{password}}",
    "scope": "openid email profile offline_access",
    "audience": "calculator-api"
}

@access_token2 = {{token2.response.body.$.access_token}}
@id_token2 = {{token2.response.body.$.id_token}}
@refresh_token2 = {{token2.response.body.$.refresh_token}}


###

# Double Calucator API
GET http://localhost:5001/api/double/3
Authorization: Bearer {{access_token}}

###

# Square Calucator API
GET http://localhost:5001/api/square/3
Authorization: Bearer {{access_token2}}

###

# Tokeninfo Calucator API
GET http://localhost:5001/api/tokeninfo
Authorization: Bearer {{access_token}}

###

# Tokeninfo Calucator API
GET http://localhost:5001/api/tokeninfo
Authorization: Bearer {{access_token2}}

###
# Refresh Token for Ressource Owner App
POST https://apisummit.eu.auth0.com/oauth/token
Content-Type: application/json

{
    "grant_type": "refresh_token",
    "client_id": "{{client_id}}",
    "client_secret": "{{client_secret}}",
    "refresh_token": "{{refresh_token2}}"
}
