##########
#
# Implict Flow
#
# https://auth0.com/device-flow/#!
# https://auth0.com/docs/authorization/flows/call-your-api-using-the-device-authorization-flow
#
##########


#####
# Configuration --> use Native App in Auth0  and enable Device Code Grant

@client_id = oEQe87AESxcAWqFD5xmTnAnOT5nBuCaT
@client_secret = pcKGiR8Er0kcKcwNKvb5wtEBSd9jLFQ8h3mhKwGe5ZAJv09jf6dqedAOR-OOCxx5

#
#####

# Get Device Code
# @name devicecode

POST https://{{tenant}}/oauth/device/code
Content-Type: application/x-www-form-urlencoded

client_id={{client_id}}
&scope=openid email profile offline_access calc:double
&audience={{audience}}


###

@device_code = {{devicecode.response.body.$.device_code}}
@user_code = {{devicecode.response.body.$.user_code}}

# Get Token
# @name token


POST https://{{tenant}}/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=urn:ietf:params:oauth:grant-type:device_code
&client_id={{client_id}}
&client_secret={{client_secret}}
&device_code={{device_code}}

###

@access_token = {{token.response.body.$.access_token}}
@id_token = {{token.response.body.$.id_token}}

# Get Userinfo with identity token
GET https://{{tenant}}/oauth/userinfo
Authorization: Bearer {{access_token}}

###

# Double Calucator API
GET {{api}}/double/3
Authorization: Bearer {{access_token}}

###

# Square Calucator API
GET {{api}}/square/3
Authorization: Bearer {{access_token}}

###

# Tokeninfo Calucator API
GET {{api}}/identity
Authorization: Bearer {{access_token}}
