##########
#
# Auth0 Management API
#
# https://auth0.com/docs/api/management/v2
#
##########




# Get access token
# @name token
POST https://{{tenant}}/oauth/token
Content-Type: application/json

{
    "client_id": "{{admin_client_id}}",
    "client_secret": "{{admin_client_secret}}",
    "audience": "https://{{tenant}}/api/v2/",
    "grant_type": "client_credentials"
}

###

@access_token = {{token.response.body.$.access_token}}

# Create  Implicit Web Application
# @name create
POST https://{{tenant}}/api/v2/clients
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "is_token_endpoint_ip_header_trusted": false,
    "name": "Implicit Web Application",
    "is_first_party": true,
    "oidc_conformant": true,
    "callbacks": [
        "http://localhost:3000/signin-auth0"
    ],
    "allowed_logout_urls": [
        "http://localhost:3000/"
    ],
    "token_endpoint_auth_method": "client_secret_post",
    "app_type": "regular_web",
    "grant_types": [
        "implicit"
    ],
    "custom_login_page_on": true
}

###

@client_id = {{create.response.body.$.client_id}}

GET https://{{tenant}}/api/v2/clients/{{client_id}}
Authorization: Bearer {{access_token}}
