##########
#
# Implict Grant
#
# https://auth0.com/docs/authorization/flows/implicit-flow-with-form-post
#
##########


#####
# Configuration --> use Single Page App in Auth0

@client_id= OvyhJsTW2V7m7nN1Y2rBWtwPhSrcgWlZ
@redirect_uri = http://localhost:3000/signin-auth0
@scope = openid email profile calc:square

#
#####


# Get identity and access token
GET https://{{tenant}}/authorize?scope={{scope}}&audience={{audience}}&response_type=id_token%20token&client_id={{client_id}}&redirect_uri={{redirect_uri}}&nonce=12345789&prompt=consent

###

@access_token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1FRkdRamN4UkVKRk9FRXdRMFUwTmpjME56bENNa016UmpFMFFUVTNNME16UlVSQk9ERXhNZyJ9.eyJpc3MiOiJodHRwczovL2FwaXN1bW1pdC5ldS5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWJmMTMwZGM1YTAwYWYyMjE5ZGM5ZTUzIiwiYXVkIjpbImh0dHA6Ly9jYWxjdWxhdG9yLWFwaSIsImh0dHBzOi8vYXBpc3VtbWl0LmV1LmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3MTc5NjU4MDIsImV4cCI6MTcxNzk3MzAwMiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBjYWxjOnNxdWFyZSIsImF6cCI6Ik92eWhKc1RXMlY3bTduTjFZMnJCV3R3UGhTcmNnV2xaIn0.c2diAUP0KgHSJA6uohjIhh_BVVKYDcnYJEhgmLx5Y8PZqithGhg27Rnpq1HN8-wqG-eJjVVsB7imaI5DDqrE0TPxw9YJnAda-r3tvk8i3m7hhDfQNFex_U8Bd49PWSjuNY9fQFFOlWtWH9gDOfiVyvcJCZHhcI_v9dZ0GLStK6-F4bxZbU-95V2eWPknDI0okdriE7hOo1NAb1aBsLzGFkh9eENoys8yURy0BoLfehr1EcE-6GJpcLOFvLYhFvSglUExl4Zv4gGUBclgiGtbGLVwi6fyavhoI_rNtsn_c6BmT183m_23U54xcdcRC8e3QtPqi2b5KtL8QEK2nKkNuw
@id_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImpvaG5kb2UiLCJuYW1lIjoiam9obmRvZUBhY21lLmluYyIsInBpY3R1cmUiOiJodHRwczovL3MuZ3JhdmF0YXIuY29tL2F2YXRhci9mYzAzZjhkODZiODdmODA0NDNkMjIzNGQxYjVhYWZlZD9zPTQ4MCZyPXBnJmQ9aHR0cHMlM0ElMkYlMkZjZG4uYXV0aDAuY29tJTJGYXZhdGFycyUyRmpvLnBuZyIsInVwZGF0ZWRfYXQiOiIyMDI0LTA2LTA5VDIwOjQzOjE0LjEzMFoiLCJlbWFpbCI6ImpvaG5kb2VAYWNtZS5pbmMiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vYXBpc3VtbWl0LmV1LmF1dGgwLmNvbS8iLCJhdWQiOiJPdnloSnNUVzJWN203bk4xWTJyQld0d1BoU3JjZ1dsWiIsImlhdCI6MTcxNzk2NTgwMiwiZXhwIjoxNzE4MDAxODAyLCJzdWIiOiJhdXRoMHw1YmYxMzBkYzVhMDBhZjIyMTlkYzllNTMiLCJhdF9oYXNoIjoiNk1IWWE5WHVUeFlGd0ZqTEZRUWtYUSIsInNpZCI6IkFRVjhhRm9OYTN3WEswcW1PV0FEM3ZlNjJ3X0UtZ3pSIiwibm9uY2UiOiIxMjM0NTc4OSJ9.OG0KxYcv2QAekfYu45IlcQFPsl5KGELt6jAleM7TAe0

# Get Userinfo with identity token
GET https://{{tenant}}/userinfo
Authorization: Bearer {{access_token}}

###

# Double Calucator API
GET {{api}}/double/3
Authorization: Bearer {{access_token}}

###

# Square Calucator API
GET {{api}}/square/3
Authorization: Bearer {{access_token}}

###

# Tokeninfo Calucator API
GET {{api}}/identity
Authorization: Bearer {{access_token}}
