##########
#
# Authorization Code Grant
#
# https://auth0.com/docs/api-auth/tutorials/authorization-code-grant
#
##########


#####
# Configuration --> use Regular Web App in Auth0

@client_id= 4ukp032ZN0QLrXg0KpgqC2gWqItKdS5q
@client_secret = znIuk-qklH7oX-Dvs6Oec-mWHniXqqBvv6xNhGTvV2nIAsXvyQxRxuEUn-N44BKC
@redirect_uri = http://localhost:3000/signin-auth0

#
#####


# Get authorization Code
GET https://{{tenant}}/authorize?audience={{audience}}&scope=openid%20email%20profile%20offline_access%20calc%3Adouble&response_type=code&client_id={{client_id}}&redirect_uri={{redirect_uri}}&state=l337&prompt=consent

###


# Get access token
# @name token

@code = K8ryHbFs1jULwAFz

POST https://{{tenant}}/oauth/token
Content-Type: application/json

{
    "grant_type": "authorization_code",
    "client_id": "{{client_id}}",
    "client_secret": "{{client_secret}}",
    "code": "{{code}}",
    "redirect_uri": "{{redirect_uri}}"
}

###

@access_token = {{token.response.body.$.access_token}}
@id_token = {{token.response.body.$.id_token}}
@refresh_token = {{token.response.body.$.refresh_token}}

# Refresh token
# @name token2
POST https://{{tenant}}/oauth/token
Content-Type: application/json

{
    "grant_type": "refresh_token",
    "client_id": "{{client_id}}",
    "client_secret": "{{client_secret}}",
    "refresh_token": "{{refresh_token}}"
}

###

@access_token2 = {{token2.response.body.$.access_token}}
@id_token2 = {{token2.response.body.$.id_token}}

# Double Calucator API
GET http://localhost:5001/api/double/3
Authorization: Bearer {{access_token}}

###

# Tokeninfo Calucator API
GET http://localhost:5001/api/tokeninfo
Authorization: Bearer {{access_token}}

###

# Tokeninfo Calucator API
GET http://localhost:5001/api/tokeninfo
Authorization: Bearer {{access_token2}}

###

# Revoke refesh token
POST https://{{tenant}}/oauth/revoke
Content-Type: application/json

{
    "client_id": "{{client_id}}",
    "client_secret": "{{client_secret}}",
    "token": "{{refresh_token}}",
    "token_type_hint": "refresh_token"
}

###

# Refresh token -> fails
POST https://{{tenant}}/oauth/token
Content-Type: application/json

{
    "grant_type": "refresh_token",
    "client_id": "{{client_id}}",
    "client_secret": "{{client_secret}}",
    "refresh_token": "{{refresh_token}}"
}
